version: '3'

networks:
  inception:
    driver: bridge


volumes:
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $HOME/data/wordpress
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $HOME/data/mariadb


services:
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    image: nginx
    networks:
      - inception
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: on-failure
    ports:
      - "443:443"
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    image: wordpress
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: on-failure
    expose:
      - "9000"
    depends_on:
      - mariadb
